arb-dir: lib/l10n
template-arb-file: app_it.arb
output-dir: lib/generated
output-class: AppLocalization
output-localization-file: app_localizations.dart
nullable-getter: false
use-named-parameters: true